export const SAVE_ASSET_REQUEST = "SAVE_ASSET_REQUEST";
export const FETCH_ASSET_REQUEST = "FETCH_ASSET_REQUEST";
export const UPDATE_ASSET_REQUEST = "UPDATE_ASSET_REQUEST";
export const DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST";
export const ASSET_SUCCESS = "ASSET_SUCCESS";
export const ASSET_FAILURE = "ASSET_FAILURE";

export const FETCH_ASSETS_REQUEST = "FETCH_ASSETS_REQUEST";
export const ASSETS_SUCCESS = "ASSETS_SUCCESS";
export const ASSETS_FAILURE = "ASSETS_FAILURE";